---
- name: Update package list and show Ubuntu version on WSL Ubuntu
  hosts: localhost
  connection: local
  become: true  # enable privilege escalation

  tasks:
  - name: Update package list
    apt:
      update_cache: yes  # update the package list

  - name: Show Ubuntu version
    command: lsb_release -a  # run the lsb_release -a command and register its output
    register: ubuntu_version

  - name: Display Ubuntu version
    debug:
      var: ubuntu_version.stdout_lines  # display the output of the lsb_release -a command
